### ISSUE TITLE
Wrong DPI when using suse-prime in nvidia mode

### ISSUE THREAD

**Issue by sndirsch** [openSUSE/SUSEPrime#14]
See https://bugzilla.suse.com/show_bug.cgi?id=1130723

**Comment by simopil** [comment]
7c50a32

**Comment by sndirsch** [comment]
> [7c50a32](https://github.com/openSUSE/SUSEPrime/commit/7c50a32840e54c2129fce583a6c808bcbe5d7b5f) my xorg-nvidia.conf looks like this everytime

Merged
