### ISSUE TITLE
Unable to switch to Nvidia driver after update

### ISSUE THREAD

**Issue by zelgood** [openSUSE/SUSEPrime#21]
I recently updated to the newest version of Suse-Prime (I was previously using 0.6.8), and ran into an issue of being unable to switch to the Nvidia driver. While it previously worked fine, any attempt to switch to the driver causes it to default to the Intel driver. Looking at the log, it appears that even when forcing to boot into Nvidia, it forces it back to Intel saying the card is not found. I can use bios to force the Nvidia card on, but it appears something is preventing it from turning on in the Hybrid case

**Comment by sndirsch** [comment]
I  need to admit, that the last version of suse-prime still working for  me, was 0.5, i.e. before all the changes for systemd came in ...
--

**Comment by NickLion** [comment]
@zelgood same for me, current suse-prime was split into old (0.5) suse-prime and new (0.6.11) suse-prime-beta. Neither is working for me — 0.5 doesn't work with bbswitch, and 0.6.11 just can't enable nvidia as in your case. So I've reverted to 0.6.8 in my local repository:
https://download.opensuse.org/repositories/home:/NickLion:/prime/openSUSE_Tumbleweed/

**Comment by sndirsch** [comment]
> @zelgood same for me, current suse-prime was split into old (0.5) suse-prime and new (0.6.11) suse-prime-beta. Neither is working for me — 0.5 doesn't work with bbswitch, and 0.6.11 just can't enable nvidia as in your case. So I've reverted to 0.6.8 in my local repository:
> https://download.opensuse.org/repositories/home:/NickLion:/prime/openSUSE_Tumbleweed/

Yes, moved 0.6.11 to suse-prime-beta, and reintroduced 0.5 for suse-prime package in X11:XOrg, since suse-prime is the devel project for factory/TW. And I still don't want to switch to 0.6.x for factory/TW, let alone sle15-sp1/Leap 15.1.

**Comment by bubbleguuum** [comment]
@sndirsch 
@NickLion 

Is it still an issue using the latest master version ?

If you have any issue can you report all of this info:

1. output of:
`sudo lspci | grep VGA`
`sudo lspci | grep NVIDIA`
rpm -q bbswitch
lsmod | grep bbswitch
cat /etc/modprobe.d/09-nvidia-blacklist.conf
 systemctl status prime-select

2. Whether you are starting Xorg with a Display manager (if so which one: SDDM, etc) or using startx on a console

3. Whether you have Plymouth enabled or disabled

4. All the steps that lead to the failure with a good description (even if it seems obvious)

5. the output of `prime-select log-view` after the failure

I must say I have no issue with the script in its current (master) state after I fixed some startx issue (not using a DM here).

**Comment by NickLion** [comment]
> Is it still an issue using the latest master version ?
Sorry, I'm using other approach now, which is based on suse-prime 0.5 and switching off nvidia card using Linux PM (without bbswitch).

> 2. Do you have a locale different than the default locale ? If so which one. Reason: script greps various strings and I wonder if it is entirely compatible with non default locale.
Yes, Ukrainian, but 0.6.8 worked fine at the same time as 0.6.11 didn't.

> 3. Whether you are starting Xorg with a Display Manager (if so, which one: SDDM, GDM, etc) or using startx on a console
SDDM.

> 4. Whether you have Plymouth enabled or disabled
Completely removed.

> 5. All the steps that lead to the failure with a good description (even if it seems obvious)
a) `sudo prime-select nvidia` + relogin — still runs on intel
b) next boot nvidia + reboot — still runs on intel
NVidia was on, but it was switched off when suse-prime should make it work. Here is some logs (3 boots), when I've tried to play around it: http://susepaste.org/view/69845348

**Comment by simopil** [comment]
Using linux PM sounds good for me. At first my project was based to nouveau (when it's loaded nvidia card remains off) but didn't work for all users. Now I'm using another bbswitch version (dkms-bbswitch), but I had to edit script and lock some packages in zypper to make it works

**Comment by sndirsch** [comment]
@bubbleguuum Seems suse-prime-beta 0.6.14 meanwhile works for me. I haven't tried suse-prime-beta-bbswitch yet, since bbswitch-kmp-default wasn't available for my kernel. I was testing on a Dell Precision 5510 on sle15-sp1 (similar/identical to Leap 15.1). locale: de_DE.UTF8, Intel Skylake/nvidia GM107GLM [Quadro M1000M], no bbswitch installed, gdm/GNOME, plymouth disabled via nvidia package driver installed, no external monitors plugged

**Comment by sndirsch** [comment]
Meanwhile we're on SUSEPrime 0.7 with a lot of changes. Let's assume things are fixed. Otherwise please open a new issue.
