### ISSUE TITLE
Ask to logout 

### ISSUE THREAD

**Issue by JeffLabonte** [openSUSE/SUSEPrime#22]
Hey guys! 

I was thinking about adding a input to ask for users if they want to logout right now to complete the switch, but I saw a function called : `logout_switch`. I don't quite understand it and I am wondering if it isn't already implemented and that it doesn't work on my machine!

Thank you guys for your work! It works great!

**Comment by sndirsch** [comment]
I'm afraid you would better ask simopil <painkilla96@gmail.com>, since he introduced logout_switch.

**Comment by sndirsch** [comment]
commit 0ffbbe495840bf649ba6199a878b2473eb171bad

**Comment by Rush** [comment]
Can you make "Ask to logout" configurable? It seems that restarting X seems to be good enough to switch the direct rendering backend ...

**Comment by sndirsch** [comment]
I believe we can live with "Logout to switch graphics" here. I also don't want to change the script to an interactive script here, .because e.g. it's being used by SUSE's nvidia gfx driver packages in %post, which then would fail. It may be used by other software as well.
