### ISSUE TITLE
systemd service doesn't start

### ISSUE THREAD

**Issue by sudopluto** [openSUSE/SUSEPrime#27]
Hi all,

I am currently on Leap 15.1 with latest updates.
The suse-prime in the repos can't turn off my nvidia card, 
so I decided to try the beta rpm.

In the beta rpm, the systemd service can't start:

```
pranav@pranav-notebook:~> sudo systemctl start  prime-select.service
[sudo] password for root: 
Failed to start prime-select.service: Unit prime-select.service is not loaded properly: Exec format error.
See system logs and 'systemctl status prime-select.service' for details.
pranav@pranav-notebook:~> sudo systemctl status prime-select.service
● prime-select.service - Prime Select Service
   Loaded: error (Reason: Exec format error)
   Active: inactive (dead)

Jul 06 03:15:45 localhost systemd[1]: /usr/lib/systemd/system/prime-select.service:7: Executable path is not absolute: prime-select apply-current
Jul 06 03:15:45 localhost systemd[1]: prime-select.service: Cannot add dependency job, ignoring: Unit prime-select.service is not loaded properly: Exec format error.
Jul 06 03:15:47 localhost systemd[1]: /usr/lib/systemd/system/prime-select.service:7: Executable path is not absolute: prime-select apply-current
Jul 06 03:15:48 localhost systemd[1]: /usr/lib/systemd/system/prime-select.service:7: Executable path is not absolute: prime-select apply-current
Jul 06 03:15:48 localhost systemd[1]: /usr/lib/systemd/system/prime-select.service:7: Executable path is not absolute: prime-select apply-current
Jul 06 03:15:48 localhost systemd[1]: /usr/lib/systemd/system/prime-select.service:7: Executable path is not absolute: prime-select apply-current
Jul 06 03:16:49 pranav-notebook systemd[1]: /usr/lib/systemd/system/prime-select.service:7: Executable path is not absolute: prime-select apply-current
Jul 06 03:18:02 pranav-notebook systemd[1]: /usr/lib/systemd/system/prime-select.service:7: Executable path is not absolute: prime-select apply-current
Jul 06 03:24:17 pranav-notebook systemd[1]: /usr/lib/systemd/system/prime-select.service:7: Executable path is not absolute: prime-select apply-current

```

I don't know what this means, or if this is even helpful.

**Comment by simopil** [comment]
To get nvidia card off you must use suse-prime-beta-bbswitch instead suse-prime-beta

**Comment by sndirsch** [comment]
Indeed there is such service file in the non-bbswitch package beta package. Seems to be some old service file not belonging to any package. Please remove and use suse-prime-beta-bbswitch  instead.

**Comment by sudopluto** [comment]
My bad, I was trying to install via rpm and not repo, so I missed that package.Sorry for not doing my homework before opening bug. 

However, when I installed, I had the opposite problem where I was unable to wake up the nvidia card.
Weird.

**Comment by simopil** [comment]
Which nvidia drivers are you using? Is nouveau driver correctly blacklisted? Is bbswitch installed? Post suse-prime log (prime-select log-view)

**Comment by sudopluto** [comment]
Sorry, I am no longer on opensuse, so I can't provide the logs. I am just trying to setup my laptop, and so I'm just trying to get stuff to work asap.

But I remember there being nothing out of the ordinary in the logs.

I had a fresh install of Leap 15.1 with whatever the latest nvidia drivers were for it (I was using the opensues nvidia repo). I have hardlocks with nouveau enabled, so that was disabled via modprobe.blacklist=nouveau even before installing nvidia drivers.

bbswitch was installed, but I am not sure if it was working correctly with my hardware. My issue seems to be very closely related to #21.

I am since using nvidia-xrun on fedora, and that seems to be working much better. They use linux's inbuilt PM, and that seems to work much better with my hardware.
