### ISSUE TITLE
Update version on Tumbleweed repos.

### ISSUE THREAD

**Issue by DevDorrejo** [openSUSE/SUSEPrime#28]
Hello, the version here and on the tumbleweed repos are totally differently and need to be updated.

**Comment by sndirsch** [comment]
I need to admit, that the last version of suse-prime still working for me, was 0.5, i.e. before all the changes for systemd came in. Nevertheless I'm packaging the latest release here:
https://build.opensuse.org/package/show/X11:XOrg/suse-prime-beta

**Comment by bubbleguuum** [comment]
But what exactly is not working for you ?
I vaguely remember asking for details in another bug report but I do not think you ever responded.

**Comment by sndirsch** [comment]
@bubbleguuum I no longer remember the details. It was related to systemd IIRC. I tried hard for half an hour getting it to work, but gave up in the end. And then other things were more important ...

**Comment by bubbleguuum** [comment]
It's true that the script is not the easiest thing to understand to troubleshoot issues...
However, it's been working fine on my setup. But I'm not using the package you have made (maybe I should) and installed everything manually.

**Comment by sndirsch** [comment]
@bubbleguuum Yeah. Maybe that's the first thing you may want to try. Give my package a try. Maybe I packaged something stupid.

**Comment by bubbleguuum** [comment]
I will test it.

Can you just give me some quick details on your setup:

- what is the locale of your install (en_US I suppose)
-  output of:
    sudo lspci | grep VGA
    sudo lspci | grep NVIDIA
- do you have bbswicth installed ? 
- what Display Manager (if any) and Desktop environment you use ?
- whether you have Plymouth enabled or disabled

**Comment by sndirsch** [comment]
@bubbleguuum Seems suse-prime-beta 0.6.14 meanwhile works for me. I haven't tried suse-prime-beta-bbswitch yet, since bbswitch-kmp-default wasn't available for my kernel. I was testing on a Dell Precision 5510 on sle15-sp1 (similar/identical to Leap 15.1). locale: de_DE.UTF8, Intel Skylake/nvidia GM107GLM [Quadro M1000M], no bbswitch installed, gdm/GNOME, plymouth disabled via nvidia package driver installed, no external monitors plugged

**Comment by bubbleguuum** [comment]
@sndirsch 

I haven't tried yet to test packages yet since I'm currently looking at various strings the script is grepping and that could fail on some systems. Can you tell me if this returns anything for you:

`sudo journalctl | grep "pam_unix(gdm-password:session): session closed"`

**Comment by bubbleguuum** [comment]
@sndirsch 

I have now tested suse-prime-beta-bbswitch 0.6.14 extensively and found no problem with it. Setup:

- Lenovo Thinkpad P72 with Intel UHD 630 + Quadro P600
- latest TW as of yesterday (not tested on Leap 15.1 so if there are problem with it, I wouldn't know)
- locale: fr_FR  (to test with something else than the default English locale)
- tested with SDDM, GDM and no Desktop Manager (multi-user.target)
- plymouth disabled via nvidia package driver installed

**Comment by sndirsch** [comment]
> @sndirsch
> 
> I haven't tried yet to test packages yet since I'm currently looking at various strings the script is grepping and that could fail on some systems. Can you tell me if this returns anything for you:
> 
> `sudo journalctl | grep "pam_unix(gdm-password:session): session closed"`

Yes, indeed this returns two lines on my machine.

**Comment by sndirsch** [comment]
> > `sudo journalctl | grep "pam_unix(gdm-password:session): session closed"`
>
> Yes, indeed this returns two lines on my machine.

Aug 29 13:06:39 g153 gdm-password][3167]: pam_unix(gdm-password:session): session closed for user tux
Aug 30 12:02:14 g153 gdm-password][4323]: pam_unix(gdm-password:session): session closed for user tux

**Comment by sndirsch** [comment]
Just submitted latest SUSEPrime 0.7 to Tumbleweed. :-) Finally closing. ;-)
