### ISSUE TITLE
Panel name(s) in #26 are not universal

### ISSUE THREAD

**Issue by simopil** [openSUSE/SUSEPrime#35]
Laptop panel names in #26 fix are different in my config. With xrandr -q : 
intel2:  LVDS1
intel:    LVDS-1
nvidia: LVDS-1-1
Is a "getting panel names" function necessary? I haven't ScreenScaleFactor section in my kdeglobals and I haven't scaling issues.

**Comment by sndirsch** [comment]
I guess we should ask @bubbleguuum here. I see eDP-1-1/eDP-1/eDP1 in xrandr (same as in current code) and on my system /sys/class/drm/card0-eDP-1. Possibly we can conclude from /sys/class/drm files  to the right values for xrandr. How does it look like in your /sys/class/drm directory?

**Comment by sndirsch** [comment]
@simopil @bubbleguuum And AFAICS the code only works when you're running prime-select.sh via 
sudo. ...

**Comment by simopil** [comment]
Yes, I have "card0-LVDS-1" in /sys/class/drm/ directory

**Comment by sndirsch** [comment]
> Yes, I have "card0-LVDS-1" in /sys/class/drm/ directory
Wonderful. So one could check for LVDS in /sys/class/drm/, and then use the values of the initial comment or otherwise use the values of the current code. I don't think anything else is currently on the market ...

**Comment by sndirsch** [comment]
@simopil Could you verify whether my new pull request #38 fixes the issue?

**Comment by sndirsch** [comment]
Fixed with pull request #38 being accepted and included in release 0.7.3.
