### ISSUE TITLE
SUSEPrime AMD

### ISSUE THREAD

**Issue by neoacevedo** [openSUSE/SUSEPrime#37]
Hi, I have the following machine:

- Azus x570zd
- AMD Ryzen 5 2500U with Radeon Vega Mobile GFX
- 16GB RAM
- Discreet Nvidia Geforce GTX 1050

I have had a lot of issues to use hybrid graphics. Searching I found this link that solved my issue for a while:
https://devtalk.nvidia.com/default/topic/1055357/amd-ryzen-7-integrated-gpu-nvidia-1650-in-same-linux-machine-cause-xorg-to-default-to-outdated-drivers/?offset=15

In short words: when installing the privative Nvidia driver from the oficial repository, the installer doesn't create the file /usr/share/X11/xorg.conf.d/10-nvidia.config so, once I created this file with the configuration provided by Nvidia in the post https://devtalk.nvidia.com/default/topic/1056652/linux/amd-ryzen-7-geforce-gtx-1660-ti-laptop-gt-cannot-get-nvidia-to-be-used-as-primary-graphics/post/5360651/#5360651 and after that I installed **suse-prime** and finally I got it working.

With the latest updates in October for SUSEPrime, I'm having now this issue:

> Forcing nvidia due to Intel card not found

Doesn't matter if I run **prime-select intel** and shutdown/reboot/logout. Prime is forcing to use Nvidia. I know this laptop doesn't have Intel, but the solution posted by Nvidia worked before 0.7.1 upgrade.

Could SUSEPrime to work with AMD just as it works with Intel?

**Comment by sndirsch** [comment]
I guess the script may work again when you adjust the definition of 'lspci_intel_line' in /usr/bin/prime-select (maybe just replace "Intel" with "AMD"; check lspci output!). Indeed suse-prime has never been developed to support also AMD/NVIDIA combos, let alone tested with such a hardware configuration.

**Comment by sndirsch** [comment]
> I guess the script may work again when you adjust the definition of 'lspci_intel_line' in /usr/bin/prime-select (maybe just replace "Intel" with "AMD"; check lspci output!). Indeed suse-prime has never been developed to support also AMD/NVIDIA combos, let alone tested with such a hardware configuration.

@neoacevedo So have you given this a try?

**Comment by neoacevedo** [comment]
I'm sorry.
Yes, I tried and it didn't work, so I decided to uninstall it because no other method/package worked.

**Comment by sndirsch** [comment]
Ok. Then let's close that issue, since AMD/NVIDIA is still considered unsupported.
