### ISSUE TITLE
/usr/lib/udev/rules.d/90-nvidia-udev-pm-G05.rules:2 Invalid key/value pair, ignoring

### ISSUE THREAD

**Issue by bubbleguuum** [openSUSE/SUSEPrime#40]
Using suse-prime 0.7.3-2.1 with TW20191124, there are these warnings on boot:

> Nov 27 11:04:12 p72 systemd-udevd[556]: /usr/lib/udev/rules.d/90-nvidia-udev-pm-G05.rules:2 Invalid key/value pair, ignoring.
> Nov 27 11:04:12 p72 systemd-udevd[556]: /usr/lib/udev/rules.d/90-nvidia-udev-pm-G05.rules:3 Invalid key/value pair, ignoring.
> Nov 27 11:04:12 p72 systemd-udevd[556]: /usr/lib/udev/rules.d/90-nvidia-udev-pm-G05.rules:6 Invalid key/value pair, ignoring.
> Nov 27 11:04:12 p72 systemd-udevd[556]: /usr/lib/udev/rules.d/90-nvidia-udev-pm-G05.rules:7 Invalid key/value pair, ignoring.
> Nov 27 11:04:12 p72 systemd-udevd[556]: /usr/lib/udev/rules.d/90-nvidia-udev-pm-G05.rules:10 Invalid key/value pair, ignoring.
> Nov 27 11:04:12 p72 systemd-udevd[556]: /usr/lib/udev/rules.d/90-nvidia-udev-pm-G05.rules:11 Invalid key/value pair, ignoring.
> Nov 27 11:04:12 p72 systemd-udevd[556]: /usr/lib/udev/rules.d/90-nvidia-udev-pm-G05.rules:14 Invalid key/value pair, ignoring.
> Nov 27 11:04:12 p72 systemd-udevd[556]: /usr/lib/udev/rules.d/90-nvidia-udev-pm-G05.rules:15 Invalid key/value pair, ignoring.
> Nov 27 11:04:12 p72 systemd-udevd[556]: /usr/lib/udev/rules.d/90-nvidia-udev-pm-G05.rules:16 Invalid key/value pair, ignoring.
> Nov 27 11:04:12 p72 systemd-udevd[556]: /usr/lib/udev/rules.d/90-nvidia-udev-pm-G05.rules:17 Invalid key/value pair, ignoring.
> Nov 27 11:04:12 p72 systemd-udevd[556]: /usr/lib/udev/rules.d/90-nvidia-udev-pm-G05.rules:20 Invalid key/value pair, ignoring.
> Nov 27 11:04:12 p72 systemd-udevd[556]: /usr/lib/udev/rules.d/90-nvidia-udev-pm-G05.rules:21 Invalid key/value pair, ignoring.
> Nov 27 11:04:12 p72 systemd-udevd[556]: /usr/lib/udev/rules.d/90-nvidia-udev-pm-G05.rules:22 Invalid key/value pair, ignoring.
> Nov 27 11:04:12 p72 systemd-udevd[556]: /usr/lib/udev/rules.d/90-nvidia-udev-pm-G05.rules:23 Invalid key/value pair, ignoring.

**Comment by sndirsch** [comment]
This is embarassing! Definitely my fault. Fixed in release version 0.7.4.
