### ISSUE TITLE
Unable to open Snaps, flatpaks, and possibly other software

### ISSUE THREAD

**Issue by JeffLabonte** [openSUSE/SUSEPrime#41]
Hi everyone! 

I wanted to take the time to report a bug I have been subject of.

I have installed a fresh version of Tumbleweed and installed the nvidia drivers like I normally do with the documentation provided by the openSUSE community. I ran the following  command after a reboot: 

`sudo prime-select intel2`

When I completed the switch by login out and back in, I couldn't run any of my snaps and flatpaks. 

They would complain that there is `no protocol specified` and then print that it couldn't connect to the display.

**EDIT: Something I have noticed also, is that I had vertical lines that would appear and disappear in my `konsole` terminal.

**Comment by sndirsch** [comment]
I don't know the internas of snap and flatpak. My guess is, that it tries to use the NVIDIA libGL if it exists, which no longer can work, when you switch to Intel mode.

**Comment by sndirsch** [comment]
I suggest to uninstall nvidia driver if you don't want to use it and you need snap/flatpak.

**Comment by simopil** [comment]
Hi
If you want, you can do a simple test.
Try (don't use prime-select command) to go in multi-user (systemctl isolate multi-user.target), then return back in graphical mode (systemctl isolate graphical.target).
If your software still not work, the issue is the init cycle switch, otherwise if snap/flatpack work the issue is graphics-related.
Thanks

**Comment by sndirsch** [comment]
> If you want, you can do a simple test.
> Try (don't use prime-select command) to go in multi-user (systemctl isolate multi-user.target), then return back in graphical mode (systemctl isolate graphical.target).
> If your software still not work, the issue is the init cycle switch, otherwise if snap/flatpack works the issue is graphics-related.

@JeffLabonte Could you please have a try and report about the outcomings? Things may have improved already since release [0.7.5](https://github.com/openSUSE/SUSEPrime/releases/tag/0.7.5).
