### ISSUE TITLE
SUGGESTION - Allow to force the Nvidia to be turned off

### ISSUE THREAD

**Issue by JeffLabonte** [openSUSE/SUSEPrime#42]
Hi there! It would be great to have the possibility to turn off the nvidia GPU completely when you have the latest Nvidia Drivers.

Some Nvidia card just like mine ( GTX 1050 ) aren't supported for power management.

Thank you guys!

**Comment by sndirsch** [comment]
Not sure, what you mean. You can disable it via bbswitch

https://github.com/openSUSE/SUSEPrime

**Comment by sndirsch** [comment]
Closing as already implemented by using bbswitch.
