### ISSUE TITLE
NetworkManager not working after switching graphics device

### ISSUE THREAD

**Issue by lutzgruber** [openSUSE/SUSEPrime#43]
Hi,

I am using SUSEPrime on a current Tumbleweed installation.

SUSEPrime requires a log out, log back in procedure after switching the graphics device. After such a log out, log in cycle, NetworkManager does not work anymore, producing the following error message when trying to connect:
```Error: Connection activation failed: No suitable device found for this connection (device wlanxxx not available because device is not available).```

I also noticed that `wpa_supplicant` is not running after such a log out, log in procedure. I can establish a wifi connection after manually starting `wpa_supplicant`, and then using `iwconfig` and `dhclient`.

Everything works again flawlessly after a reboot. Also, there are no problems after a log out, log in cycle that is not preceded by switching the graphics device with SUSEPrime.

I would be happy to provide logging and debugging output if the appropriate file locations are pointed out.

Thank you

**Comment by simopil** [comment]
Hi,
Yes I perfectly know this bug, I've found a workaround that consist to set wpa_supplicant service in autostart mode. I don't know why this happens but I think wpa supplicant don't like init switches

**Comment by sndirsch** [comment]
OMG! That's bad! :-(

**Comment by simopil** [comment]
Yes, it isn't good thing. I'll do some tests without SUSEPrime (only init switches) for wpa_supplicant and #41 issue related things too, I think issue isn't our service but init switch cycle

**Comment by simopil** [comment]
Can you post the output of "sudo cat /usr/lib/systemd/system/wpa_supplicant.service" ?
I noticed that mine isn't different from default anymore because updates, and SUSEprime works as expected with wireless networking.
Take a look to [this](https://build.opensuse.org/package/rdiff/hardware/wpa_supplicant?orev=8d9efccb0c20fb9cf70b78495d5071a9&rev=4f9c3ed981902c9210dd734d0b39ed7f#revision_details_2) wpa_supplicant service update, I think this resolved issue in my system.
Thanks

**Comment by lutzgruber** [comment]
```
sudo cat /usr/lib/systemd/system/wpa_supplicant.service
[sudo] password for root: 
[Unit]
Description=WPA Supplicant daemon
After=dbus.service network.target

[Service]
Type=dbus
BusName=fi.w1.wpa_supplicant1
ExecStart=/usr/sbin/wpa_supplicant -c /etc/wpa_supplicant/wpa_supplicant.conf -u -t -f /var/log/wpa_supplicant.log

[Install]
WantedBy=multi-user.target
```

Has the wpa_supplicant update you referenced been included into a current Tumbleweed build? I regularly run `zypper dup`, so I expect to my system to be mostly up to date.

**Comment by simopil** [comment]
Your service configuration is the same of mine

**Comment by CementMixer** [comment]
I've encountered this problem too, a temporary solution is restart NM after switching to runlevel 5:
`init 5 && systemctl restart NetworkManager`
The Optimus-manager of Arch handles this quite well, so does the ubuntu solution. Hope to see more advancements in suse!

**Comment by lutzgruber** [comment]
I confirm that running `sudo systemctl restart NetworkManager` after logging back in restores network connectivity.

Did this become a NetworkManager bug or is this still a SUSEPrime issue?

**Comment by simopil** [comment]
You can try switch to init3 then init5 without suse prime seevice and see if NetworkManager works. In my system this bug not appens anymore so I can't try

**Comment by CementMixer** [comment]
while leave the prime-select service disabled, the issue persists. Might be a NM bug, what's the version of your NM and systemd? @simopil

**Comment by simopil** [comment]
NM 1.22.2 and systemd 243

**Comment by simopil** [comment]
Look today's 0.7.5 release, it should fix the issue

**Comment by simopil** [comment]
Look today's 0.7.5 release, it should fix the issue

**Comment by lutzgruber** [comment]
Apologies for the delay, and thank you very much for the fast fix!

My current Tumbleweed installation with suse prime 0.7.5-1.1 does not have this problem anymore!
