### ISSUE TITLE
Make the 'nvidia -> intel' switching automatic

### ISSUE THREAD

**Issue by CementMixer** [openSUSE/SUSEPrime#44]
Why can't we make the switching automatic, by running a background task before 'init 3' that wait for runlevel to switch to 3 and execute 'init 5' automatically? I myself have been using this solution and found it pretty handy (quite like optimus-manager).

**Comment by sndirsch** [comment]
Not sure what you mean exactly with make the switching automatic. Which switch? Could you elobarate?

**Comment by CementMixer** [comment]
In the readme file, it says the user must switch to runlevel 3 to switch to the intel card, so that the NVIDIA kernel module can be removed correctly. (bbswitch)

Sent from my iPhone

在 2020年1月13日，00:08，Stefan Dirsch <notifications@github.com<mailto:notifications@github.com>> 写道：


Not sure what you mean exactly with make the switching automatic. Which switch? Could you elobarate?

**Comment by sndirsch** [comment]
> In the readme file, it says the user must switch to runlevel 3 to switch to the intel card, so that the NVIDIA kernel module can be removed correctly. (bbswitch)

I don't see this in the Readme file.

**Comment by sndirsch** [comment]
Hmm. Unfortunately I'm still missing feedback here. Could be that the issue was already resolved with commit #e3ee133593cf14e325c4ecd3822921bc090526c0 (release 0.7.5). Closing now ...
