### ISSUE TITLE
Update Documentation for Dynamic Power Management?

### ISSUE THREAD

**Issue by fnorbenden** [openSUSE/SUSEPrime#46]
The readme says that the hope is to stop using dracut (or perhaps have it no longer be manual) in the future. However, none of the files listed in the readme's DPM section correspond to their current location. Could the maintainer please clarify in the docs if any additional steps are necessary beyond the installation->switch to nvidia->switch to intel to have both offloading (which appears to work out of the box) and DPM work properly (which seems to be working out of the box, but I'm having difficulty verifying)?

**Comment by sndirsch** [comment]
Fixed this with commit #5f84522

**Comment by sndirsch** [comment]
https://github.com/openSUSE/SUSEPrime/commit/5f845227f9d284ee3a1e7483aff653251ebc4f91
