### ISSUE TITLE
When I switch to "intel", I cannot use the HDMI output. Is there a workaround?

### ISSUE THREAD

**Issue by tvogel** [openSUSE/SUSEPrime#47]
When I am using "prime-select intel" with offloading (G05 driver, suse-prime-0.7.6-2.1.noarch), connecting an external screen to HDMI is not detected. When I use "prime-select nvidia", it works. Is there a way to get it working with offloading?

**Comment by sndirsch** [comment]
Sounds weird. I wouldn't have expected suse-prime to enable outputs exclusively physically connected to the NVIDIA GPU. I would say be happy that suse-prime fixed that issue for you. ;-)
Anyway, could you provide the output of "xrandr --listproviders" to us?

**Comment by sndirsch** [comment]
Are you still interested? Then could you please provide the information requested? Otherwise I need to close this issue. :-( Thanks!

**Comment by sndirsch** [comment]
Hmm. Looks like the reporter is no longer interested or available. :-( Therefore closing this ticket ...
