### ISSUE TITLE
suse-prime 0.7.6-2.1 not work properly

### ISSUE THREAD

**Issue by DevDorrejo** [openSUSE/SUSEPrime#48]
Hello, i have suseprime installed with the last version of Nvidia from the repos of nvidia and suse-prime from the OS repos.

when try unset happen this:
![image](https://user-images.githubusercontent.com/7697566/76284399-917ef880-6273-11ea-9d3f-28923b934f45.png)

when change to nvidia and try to go back to intel, the xorg config presist on the nvidia, include i can open nvidia X server settings without problem.

my laptop have a led that change of color depending if i am using intel (Blue) or Nvidia (Red), and when i change to nvidia change to red and when try to go back intel persist red and not go to blue.

**Comment by sndirsch** [comment]
I believe you found a bug in the script. Try the attached patch. [suse-prime-issue48.patch.txt](https://github.com/openSUSE/SUSEPrime/files/4311938/suse-prime-issue48.patch.txt)
@simopil @bubbleguuum

**Comment by sndirsch** [comment]
Fixed with version 0.7.7. Just released.

**Comment by sndirsch** [comment]
Closing as fixed.
