### ISSUE TITLE
[Question] AMD + NVidia

### ISSUE THREAD

**Issue by VortexAcherontic** [openSUSE/SUSEPrime#53]
Hey there I have a question regarding Notebooks which do ship with an integrated AMD GPU and a dedicated NVidia GPU.
Do they work with suse-prime as well?
Since I only ready Intel/NVidia everywhere and also only `prime-select nvidia` or `prime-select intel` or `intel2` but not AMD.
Can some just use `prime-select intel` to use an integrated AMD GPU?

**Comment by sndirsch** [comment]
Currently it's not supported. You would need to change "lspci_intel_line" in prime-select.sh accordingly (just replace" Intel" with "AMD"?). And still specify "intel" option for prime-select command for AMD-only mode ("modesetting" driver). "intel2" mode won't work. For this you would need more changes in order to use "amdgpu" or "radeon" driver instead of "modesetting" driver.

**Comment by sndirsch** [comment]
Hello Vortex! Any results? Are you still interested?

**Comment by VortexAcherontic** [comment]
@sndirsch I somehow missed someone already answered, my bad.

Yes I am still interested, I'll root this advice to the person I was asking this for.

The story was someone I know bought an AMD+NVidia notebook and had struggle with using the nvidia GPU so I suggested suse-prime. Than later on looked the package up and was questioning if this will work at all in that configuration.

I'll reply if I get any new form the one with that Notebook :)

**Comment by sndirsch** [comment]
Some references 
https://askubuntu.com/questions/1224668/hdmi-not-detected-on-asus-tuf-fx505-gtx-1660t
https://forums.developer.nvidia.com/t/nvidia-xconfig-doesnt-do-what-i-want-it-to-nor-does-nvidia-settings/107883/7

**Comment by shanthakumarvinoth** [comment]
Hello, I am having laptop with AMD/Nvidia Combo, would love to test this if you can point me in the right direction.

**Comment by sndirsch** [comment]
> Hello, I am having laptop with AMD/Nvidia Combo, would love to test this if you can point me in the right direction.

Sure. See my first comment on this topic. Looking forward to hear back from you and your results. :-) Thanks!

**Comment by fitboi** [comment]
> > Hello, I am having laptop with AMD/Nvidia Combo, would love to test this if you can point me in the right direction.
> 
> Sure. See my first comment on this topic. Looking forward to hear back from you and your results. :-) Thanks!

Hi, not the same person but I also have an AMD/Nvidia optimus laptop. I tried replacing the intel with AMD in prime-select.sh as you suggested  but powertop in that mode still shows nvidia gpu at 100%.

**Comment by sndirsch** [comment]
> > > Hello, I am having laptop with AMD/Nvidia Combo, would love to test this if you can point me in the right direction.
> > 
> > 
> > Sure. See my first comment on this topic. Looking forward to hear back from you and your results. :-) Thanks!
> 
> Hi, not the same person but I also have an AMD/Nvidia optimus laptop. I tried replacing the intel with AMD in prime-select.sh as you suggested but powertop in that mode still shows nvidia gpu at 100%.

Check this

https://github.com/openSUSE/SUSEPrime#nvidia-power-off-support-since-390xxx-driver-g04g05-driver-packages

Then run "prime-select intel". Reboot.

If this doesn't work, I can't help that much as I don't have such a combo.

**Comment by hatch01** [comment]
I opened a pull request to add AMD support, you can temporarily use my fork.

**Comment by sndirsch** [comment]
Thanks a lot! Just accepted. :-) Also made a new release out of it. 0.8.1.

**Comment by sndirsch** [comment]
Closing as fixed.
