### ISSUE TITLE
prime-select must be killed to change graphics

### ISSUE THREAD

**Issue by g7fernandes** [openSUSE/SUSEPrime#55]
If nvidia is being used and one I wish to use intel, after 
`sudo prime-select intel` and log in and out, the nvidia driver will still be in use. If i try to change again to intel I get 
```bash
"Error: a switch operation already in execution"
"You can undo it using sudo killall prime-select"
``` 
After 
```bash
sudo killall prime-select
sudo prime-select intel
```
I can log in and out (when I log out it logs in immediately even without asking for password, I don't know if it is on propose, but it is nice ) and it will be using intel with nvidia off. 
If I try to use nvidia again, I have to go through the same process. 

I'm using Opensuse Leap 15.2 with Gnome. The display manager is GDM. I have a Nvidia GTX 960.

**Comment by sndirsch** [comment]
Thanks for the report. Are you using 

a) current git master (with bbswitch package and 09-nvidia-modprobe-bbswitch-G04.conf and prime-select.service installed and the latter enabled as described in README.md) 

or 

b) suse-prime-bbswitch package from openSUSE 15.2?

**Comment by g7fernandes** [comment]
b) I'm using the suse-prime-bbswitch package 0.7.12 (from community repo). 

I noticed that if I log in and out more times it changes the driver. I suspect that sometimes it doesn't detect that I reloged. Another information. Using gnome-classic it worked with no problem (tested 3 times). 

Using GDM +  Gnome (default):

```bash
[ 09:42:47 ] Boot: setting-up nvidia card
[ 09:42:47 ] trying switch ON nvidia: [bbswitch] NVIDIA card is ON
[ 09:42:49 ] NVIDIA card correctly set
------------------------------------------------------------
sudo prime-select intel
Logout to switch graphics
------------------------------------------------------------
[ 09:43:15 ] user_logout_waiter: started
------------------------------------------------------------
<here I reloged>
-----------------------------------------------------------
$ /usr/sbin/prime-select get-current
Driver configured: nvidia
[bbswitch] NVIDIA card is ON

$ sudo prime-select intel
[sudo] password for root: 
Error: a switch operation already in execution
You can undo it using sudo killall prime-select
-----------------------------------------------------------
<No changes in the log, trying loggin out and in again>
-----------------------------------------------------------
$ /usr/sbin/prime-select get-current
Driver configured: intel
[bbswitch] NVIDIA card is OFF
-----------------------------------------------------------
<ok, now worked>
-----------------------------------------------------------
[ 09:49:08 ] user_logout_waiter: X restart detected, preparing switch to intel [ boot_state > S ]
[ 09:49:09 ] NVIDIA card will be switched off, NVIDIA offloading will not be available
[ 09:49:09 ] trying switch OFF nvidia: [bbswitch] NVIDIA card is OFF
[ 09:49:09 ] Intel card correctly set
[ 09:49:09 ] HotSwitch: starting Display Manager [ boot_state > N ]
-----------------------------------------------------------
$ sudo prime-select nvidia # changing again to nvidia 
-----------------------------------------------------------
[ 09:51:08 ] user_logout_waiter: started
-----------------------------------------------------------
<log in and out>
----------------------------------------------------------
$ /usr/sbin/prime-select get-current
Driver configured: intel
[bbswitch] NVIDIA card is OFF

-----------------------------------------------------------
<log in and out>
----------------------------------------------------------
/usr/sbin/prime-select get-current
Driver configured: intel
[bbswitch] NVIDIA card is OFF
```

If you find useful, here is my journalctl 

 https://drive.google.com/file/d/1r6T0NBbir2hJxYqctinolmakAyk7-9l_/view?usp=sharing

**Comment by sndirsch** [comment]
Could you try using this patch?
`
diff --git a/prime-select b/prime-select
index 4faaa95..f546561 100755
--- a/prime-select
+++ b/prime-select
@@ -658,7 +658,8 @@ case $type in
             
             gdm )
                #GDM_mode
-               until [ "$(journalctl --since "$currtime" | grep "pam_unix(gdm-password:session): session closed")" > /dev/null ]; do
+               until [ "$(journalctl --since "$currtime" | grep -e "pam_unix(gdm-password:session): session closed" \
+                                                                -e "pam_unix(gdm-autologin:session): session closed")" > /dev/null ]; do
                     sleep 0.5s
                done
                logging "user_logout_waiter: X restart detected, preparing switch to $2 [ boot_state > S ]"
`

**Comment by sndirsch** [comment]
Thanks for the journalctl. Tried to fix this with [this](https://github.com/openSUSE/SUSEPrime/commit/40321adc3630eab0969278a5d337fea7607c9744) commit in master. Could you have a try, please?

**Comment by sndirsch** [comment]
As background. prime-select needs to wait until the session is terminated, so it can stop displayamanger, unload nvidia kernel modules, load bbswitch module, disable NVIDIA GPU and start again displaymanager.  And vice versa when switching from intel mode to nvidia.
nvidia modules and bbswitch module don't like each other.

**Comment by sndirsch** [comment]
Patch works for me. Tested with gdm and "GNOME on Xorg". Indeed I found "pam_unix(gdm-password:session): session closed" in journalctl output.

**Comment by sndirsch** [comment]
I made a 0.7.13 release, which includes the fix. [openSUSE Devel project](https://build.opensuse.org/package/show/X11:XOrg/suse-prime) is also updated.

**Comment by sndirsch** [comment]
Closing as fixed.
