### ISSUE TITLE
Dead link in assumptions section

### ISSUE THREAD

**Issue by TauSigma5** [openSUSE/SUSEPrime#59]
![image](https://user-images.githubusercontent.com/46148925/106788092-6d28c900-6648-11eb-9ce5-d457c5de8231.png)

The link to http://opensuse-community.org/nvidia.ymp is a dead link and should be replaced with a working link. Perhaps it should be replaced with this link? https://en.opensuse.org/SDB:NVIDIA_drivers

**Comment by sndirsch** [comment]
I cannot confirm http://opensuse-community.org/nvidia.ymp being a dead link. Seems this has been a temporary issue or an issue on your side. Closing.
