### ISSUE TITLE
Breaks HDMI audio on Dell Alienware 13R3

### ISSUE THREAD

**Issue by tvogel** [openSUSE/SUSEPrime#60]
https://github.com/openSUSE/SUSEPrime/blob/2a2e1a346db966b1a67ebe05438a0e24af380269/90-nvidia-udev-pm-G05.rules#L8

"Silently" disabling this feature is a surprising side-effect. I would very much appreciate if you could note that effect in the documentation and give instructions how to re-enable HDMI audio (maybe sacrificing power-management - but in some cases that might be the easier death to die?).

BTW, on my device and even with Linux 5.10, I still needed the nvhda module but this is a different story...

**Comment by sndirsch** [comment]
Well, actually it's documented
https://github.com/openSUSE/SUSEPrime#nvidia-power-off-support-since-435xxx-driver-with-turing-gpu-and-later-g05-driver-packages

Recreate your initrd with some special settings, which are needed to enable DynamicPowerManagement and remove NVIDIA kernel modules from initrd, so some special udev rules can be applied to disable NVIDIA Audio and NVIDIA USB and make runtime PM for NVIDIA GPU active. This is needed as workaround, since NVIDIA Audio/USB currently cannot be enabled at the same time as NVIDIA GPU DynamicPowerManagement. This is easily done with:

Maybe it's missing a big red warning ...

**Comment by tvogel** [comment]
Hi,

thanks for your reply but even without taking any of the described
customizations of the initrd, just installing the package activates the
udev rules that remove the nvidia HDMI audio device.
I don't find this behavior documented. And I think, it should be optional
or at least an opt-out should be documented.

Best regards,

Tilman Vogel

Unterwegs geschrieben

Stefan Dirsch <notifications@github.com> schrieb am Di., 23. Feb. 2021,
13:56:

**Comment by sndirsch** [comment]
In case you're talking about suse-prime package this documentation is in /usr/share/doc/packages/suse-prime/README.md

**Comment by tvogel** [comment]
Hi!

I also checked /usr/share/doc/packages/suse-prime/README.md from
suse-prime-0.7.15-1.2.noarch :

That document as well es the current README.md from the repository, list
the steps to enable blacklisting and disabling HDMI audio as extra steps
(copy conf and rules files and then run mkinitrd), the user has to take in
order to enable power-off support. However, in contrast, at least the
package already places the conf and rules files at the active locations,
disabling HDMI audio automatically just by installing the package. That's
where my confusion comes from and why I suggest that this shall (again?) be
a manual step because, I don't think, one can expect that everybody who
installs suse-prime wants to sacrifice HDMI audio support. Of course it's a
pity that I cannot benefit from full power saving if I want to use HDMI
audio but if that's the case, I see two options:

1) make it a manual choice (what I am suggesting)
2) make it dependent on HDMI cable attachment and disable power-off mode
and enable HDMI audio support in that case (that would be really cool but I
guess, it's quite complicated to get right?)

Regards,

Tilman



Am Mi., 24. Feb. 2021 um 02:10 Uhr schrieb Stefan Dirsch <
notifications@github.com>:

**Comment by sndirsch** [comment]
Ok. I've improved the documentation now, made a new realease and updated the package. This should help already.

It's easier to reeanble HDMI Audio sound than to enable DynamicPowerManagement. Therefore I want  to stay with the latter as default. Whatever you chose as default it will be wrong anyway ...

**Comment by tvogel** [comment]
Thanks a lot! I will take look!

Am Mi., 24. Feb. 2021 um 12:01 Uhr schrieb Stefan Dirsch <
notifications@github.com>:
