### ISSUE TITLE
Will the last release be sent to OpenSUSE repos? 

### ISSUE THREAD

**Issue by g7fernandes** [openSUSE/SUSEPrime#62]
I'm currently using the version 0.7.17 installed with zypper. It works supper! But the latest changes from March are not available. Will 0.8 be sent to OS repos? Or is the latest version too experimental?
Thank you!

**Comment by sndirsch** [comment]
0.8 has radical changes. It will be a lot of work. And packages suse-prime/suse-prime-bbswitch need to be merged. Of course it needs a lot of testing. It's on my TODO list. Using 0.7.17 is fine. You don't lose any features with this let alone performance. But feel free to uninstall the packages and give the git 0.8 version a try on your system. Feedback would be welcome.

**Comment by sndirsch** [comment]
Just made the package update for openSUSE Factory/Tumbleweed. See [here](https://build.opensuse.org/request/show/919256)

**Comment by sndirsch** [comment]
Accepted by now. Considered done therefore.
