### ISSUE TITLE
Does this work with AMD Radeon graphics + NVIDIA?

### ISSUE THREAD

**Issue by kevinsmia1939** [openSUSE/SUSEPrime#66]
Hi,

I have a laptop with openSUSE Tumbleweed.
Processors: 12 × AMD Ryzen 5 4600H with Radeon Graphics
Graphics Processor: NVIDIA GeForce GTX 1650 Ti/PCIe/SSE2

If I understand correctly, this only work with Intel CPU?
I tried to install this, but once I switch to NVIDIA, I cannot switch to AMD integrated graphics.

Thanks.

**Comment by sndirsch** [comment]
I accepted a pull request for amd support and made a release with it with 0.8.1. Unfortunately there was a missing file. Just accepted another pull requeste, which fixes this and made a new release 0.8.2 for this. So I suggest to try again with 0.8.2.

**Comment by sndirsch** [comment]
> @sndirsch
> Do you know if KDE Plasma Wayland work with latest nvidia driver 470.63.01?

It worked for me with an older nvdiia release (haven't tested with 470.63.01). But this was with intel/nvidia combo.

**Comment by kevinsmia1939** [comment]
@sndirsch
I only see 0.7.17 in opensuse tumbleweed, is it not yet update?

**Comment by sndirsch** [comment]
> @sndirsch
> I only see 0.7.17 in opensuse tumbleweed, is it not yet update?

Yes, this is issue#62 ...

**Comment by sndirsch** [comment]
Let's assume things are working with 0.8.2 now. Otherwise please reopen. Thanks!

**Comment by kevinsmia1939** [comment]
it worked! thanks.

**Comment by sndirsch** [comment]
@kevinsmia1939 Thanks for the feedback! Credits go to @hatch01 ...

**Comment by hatch01** [comment]
It's a pleasure and thank you for your feedback
