### ISSUE TITLE
bbswitch is installed but seems broken. Cannot get NVIDIA power status

### ISSUE THREAD

**Issue by sith-on-mars** [openSUSE/SUSEPrime#67]
After the latest 20210904 upgrade which updates the kernel to 5.14, bbswitch which I use to power off Nvidia seems to stop working. Here is the output:

```
/usr/sbin/prime-select get-current
Driver configured: intel
[bbswitch] bbswitch is installed but seems broken. Cannot get NVIDIA power status
```

Should I just wait for another kernel update to fix it?

**Comment by bubbleguuum** [comment]
Looks like there is no bbswitch kmp package for 5.14 yet, thus no module.

**Comment by sith-on-mars** [comment]
Thanks! Does that mean we need to wait until Nvidia provides the kmp package for 5.14 first so that bbswitch kmp package can be updated to 5.14 as well?

**Comment by bubbleguuum** [comment]
No, we need to wait for that package to appear in Tumbleweed. Not sure why it is not already there in the first place.

**Comment by bubbleguuum** [comment]
Specifically, there's a problem building some kmp packages currently due to an rpmlint error:

https://lists.opensuse.org/archives/list/kernel@lists.opensuse.org/thread/J2T3BWW3SGKIKOACCK7BSALMHSC5TKNS/

**Comment by travis-82** [comment]
I have this issue in Leap 15.3 as well:
```
/usr/sbin/prime-select get-currentDriver configured: intel
grep: /proc/acpi/bbswitch: No such file or directory
grep: /proc/acpi/bbswitch: No such file or directory
bbswitch is installed but seems broken. Cannot get NVIDIA power status
```

**Comment by sith-on-mars** [comment]
Not quite about the Leap issue. On my Tumbleweed the issue is fixed in the 20210906 snapshot.

**Comment by sndirsch** [comment]
It is my understanding that it has been a Tumbleweed-only issue.

**Comment by sndirsch** [comment]
Closing as fixed.
