### ISSUE TITLE
Where would the config file be

### ISSUE THREAD

**Issue by memesforlife1** [openSUSE/SUSEPrime#69]
Where would the config file be for powering off the NVIDIA card when not in use(G05 Driver) ?

**Comment by sndirsch** [comment]
For Turing and later check [this](https://github.com/openSUSE/SUSEPrime#nvidia-power-off-support-since-435xxx-driver-with-turing-gpu-and-later-g05-driver-packages). For older GPUs check [that](https://github.com/openSUSE/SUSEPrime#nvidia-power-off-support-since-390xxx-driver-g04g05-driver-packages)

**Comment by sndirsch** [comment]
But things will get easier with 0.8.2 available as package for openSUSE. See issue #62.

**Comment by memesforlife1** [comment]
I know I just need to know where would I put the Turing config

**Comment by sndirsch** [comment]
You need all the 3 files, which are mentioned in [this](https://github.com/openSUSE/SUSEPrime#nvidia-power-off-support-since-435xxx-driver-with-turing-gpu-and-later-g05-driver-packages)   section.

**Comment by sndirsch** [comment]
Hope this has answered your question.
