### ISSUE TITLE
Reports on bbswitch causing boot failure on some laptops

### ISSUE THREAD

**Issue by bubbleguuum** [openSUSE/SUSEPrime#70]
With the new 0.8.2 openSUSE TW package reaching users, there has been reports of boot failures for some of them, potentially related to bbswitch. Maybe it was problematic before for some users, but only for those using the old `suse-prime-bbswitch` package, which probably was not the majority.

See this issue:

https://bugzilla.opensuse.org/show_bug.cgi?id=1190608

And my post for details:
https://bugzilla.opensuse.org/show_bug.cgi?id=1190608#c17

Maybe it would be a good idea to not enable bbswitch by default, and the user would have to manually enable it (with a new command-line parameter to prime-select.sh for example).

**Comment by sndirsch** [comment]
Thanks for letting me know! I suppose @bubbleguuum here and @Michael Pujos on Bugzilla is the same personality, right? ;-) I think the easiest would be to remove the Recommends to bbswitch package.

**Comment by sndirsch** [comment]
Better include @simopil here as well.  :-)

**Comment by bubbleguuum** [comment]
I've been discovered :)

Yes, maybe putting the bbswitch package as a Suggests rather than Recommends.
Or remove it entirely.

Also, the `prime-select service` must always be running for nvidia modules to be loaded in the nvidia configuration.
If a user disable it, Xorg will fail to start on next boot as there is nothing to load the modules (they are blacklisted). Maybe some sanity check should be done about it to avoid that situation.

**Comment by sndirsch** [comment]
I think removing bbswitch dependancy entirely would be the best. When running prime-select, you get the notice that bbswitch is not being installed when it isn't.

Within our package the service is being enabled. So unless the user disables the service intentionally, there shouldn't be an issue after next reboot.

**Comment by sndirsch** [comment]
Done.
https://build.opensuse.org/request/show/920110
