### ISSUE TITLE
Login screen keeps black 

### ISSUE THREAD

**Issue by AlfredoCubitos** [openSUSE/SUSEPrime#77]
Hi,

I'm using Tumbleweed with an Nvidia card.
I have the nvidia card enabled at boot time.
Since the last update, the login screen keeps black.

I found out that prime copies the `/usr/share/prime/xorg-nvidia.conf` to `/etc/X11/xorg.conf.d/90-nvidia.conf`

When  I empty this file `/etc/X11/xorg.conf.d/90-nvidia.conf`  the login screen appears
But this workaround may lead to other issues e.g. Steam games freezes the box.

With a complete `/etc/X11/xorg.conf.d/90-nvidia.conf` 
`systemctl status display-manager` throws a
`Auth: sddm-helper exited with 6` error

Any Ideas to fix this issue?

**System Info**
Operating System: openSUSE Tumbleweed 20220213
KDE Plasma Version: 5.24.0
KDE Frameworks Version: 5.90.0
Qt Version: 5.15.2
Kernel Version: 5.16.8-1-default (64-bit)
Graphics Platform: X11
Processors: 16 × Intel® Core™ i7-10875H CPU @ 2.30GHz
Memory: 15.4 GiB of RAM
Graphics Processor: Mesa Intel® UHD Graphics

**Comment by sndirsch** [comment]
I think this is a duplicate of https://bugzilla.suse.com/show_bug.cgi?id=1195885 Please try with kernel boot option `initcall_blacklist=simpledrm_platform_driver_init` as mentioned there.

**Comment by sndirsch** [comment]
How to achieve this. See instructions here
https://bugzilla.suse.com/show_bug.cgi?id=1195887#c14
https://bugzilla.suse.com/show_bug.cgi?id=1195887#c15

**Comment by AlfredoCubitos** [comment]
Sorry, but that issue you mentioned is different.
At least sddm starts but crashes, so I can login to a tty console. ;-)

Anyway, I tried the solution, but didn't work either.

I think that is an X authorization issue. 

I red all the SDB:Nvidia and archlinux wikis, tried all the hints but nothing works.

Any hints where to look are welcome :-)

**Comment by bomiyr** [comment]
@AlfredoCubitos Which Nvidia driver do you use? 
I have similar problem after updating to G06(v510.x). In "offload" mode only black screen with mouse pointer instead of sddm. If login in tty and execute ```sudo prime-select unset``` it's back to normal (except power consumption is higher than in 'offload' mode). Do you have the same behavior?

**Comment by AlfredoCubitos** [comment]
@bomiyr  I'm using the same driver as you.
Your solution disables the nvidia driver, this leads to the behavior  you described.

I commented out the Intel sections in the `/etc/X11/xorg.conf.d/90-nvidia.conf` file.
That works for me.
The nvidia driver is loaded and all works as expected :-)

Now the content looks like this:

```
#Section "ServerLayout"
 #   Identifier "layout"
  #  Screen "nvidia"
  #  Inactive "intel"
  #  Inactive "modesetting"
#EndSection

#Section "Screen"
 #   Identifier "intel"
 #   Device "intel"
#EndSection

#Section "Device"
#    Identifier "intel"
#    Driver "intel"
#EndSection

Section "Screen"
    Identifier "modesetting"
    Device "modesetting"
EndSection

Section "Device"
    Identifier "modesetting"
    Driver "modesetting"
EndSection

Section "Screen"
    Identifier "nvidia"
    Device "nvidia"
EndSection
```
@sndirsch What do think about this solution?

**Comment by sndirsch** [comment]
@AlfredoCubitos You didn't remove any intel section. You removed nvidia device section.

Section "Device"
    Identifier "nvidia"
    Driver "nvidia"
    BusID "PCI:X:X:X"
    Option "DPI" "96 x 96"
    Option "AllowEmptyInitialConfiguration"
    Option "AllowExternalGpus"
EndSection

I'm afraid at least for others it's still needed.

**Comment by sndirsch** [comment]
Oh no. You commented it out. You didn't remove it. But it's weird, that the nvidia device section is missing in your /etc/X11/xorg.conf.d/90-nvidia.conf

**Comment by sndirsch** [comment]
@AlfredoCubitos Seems you still have xf86-video-intel package installed. I suggest to uninstall it and I think then you can use an unmodified /etc/X11/xorg.conf.d/90-nvidia.conf.

**Comment by AlfredoCubitos** [comment]
@sndirsch sorry, that didn't work either :-( 
I removed the xf86-video-intel driver, but the problem remains.

**Comment by AlfredoCubitos** [comment]
@sndirsch sorry, that didn't work either :-( 
I removed the xf86-video-intel driver, but the problem remains.

**Comment by AlfredoCubitos** [comment]
The problem seems to be the Intel driver.
I commented out only the Intel Driver section and it works also.
@sndirsch Do you know which driver is loaded when I deinstalled the xf86-video-intel package and where where to look for errors?

**Comment by sndirsch** [comment]
First it tries`intel` X driver. If this fails (no xf86-video-intel package installed) it should load `modesetting` X driver. Could you attach your /var/log/Xorg.0.log with unmodified ` /etc/X11/xorg.conf.d/90-nvidia.conf`

**Comment by AlfredoCubitos** [comment]
here my Xorg.0.log for the original configuration.
[Xorg_intel.log](https://github.com/openSUSE/SUSEPrime/files/8082799/Xorg_intel.log)

In addition, on reboot it was not sufficient to disable only the Intel `Screen` section, I had also to disable  (uncomment) the  `ServerLayout` section.
So, on reboot the `ServerLayout` section enabled causes the same error, when the Intel Screen Section is disabled
While restart the display manager with `systemctl restart display-manager`  its sufficient only to disable the Intel Screen section

My workaround for this issue is to change the ` /usr/share/prime/xorg-nvidia.conf`
```
Section "Screen"
    Identifier "modesetting"
    Device "modesetting"
EndSection

Section "Device"
    Identifier "modesetting"
    Driver "modesetting"
EndSection

Section "Screen"
    Identifier "nvidia"
    Device "nvidia"
EndSection

Section "Device"
    Identifier "nvidia"
    Driver "nvidia"
    BusID "PCI:X:X:X"
    Option "DPI" "96 x 96"
    Option "AllowEmptyInitialConfiguration"
    Option "AllowExternalGpus"
EndSection


```

**Comment by sndirsch** [comment]
Nothing obvious in the X logfile. Please try with an older kernel and with this unmodified xorg.conf file. It still smells like this simpledrm issue.

**Comment by sndirsch** [comment]
@AlfredoCubitos Could you update this ticket, please? Is this still an issue with latest Tumbleweed and kernel? Meanwhile we (re-)enabled simpledrm in our kernel, but it's disabled by default when installing our nvidia kernel packages by adding "nosimplefb=1" as kernel boot option in %post. Please try with unmodified X config files.

**Comment by AlfredoCubitos** [comment]
This issue is solved :-)

**Comment by sndirsch** [comment]
Nice to hear this. Thanks for prompt feedback! :-)
