### ISSUE TITLE
Blacklisting nouveau, nvidia and bbswitch unnecessary on current hardware/drivers

### ISSUE THREAD

**Issue by usuallycwdillon** [openSUSE/SUSEPrime#79]
Users of -G05 and -G06 libraries (currently nvidia driver versions 470.x and 510.x) may need to move or delete the _09-nvidia-modprobe-bbswitch-G04.conf_ file under _/usr/lib/modprobe.d/_. Nvidia render offloading obviates bbswitch and prevents the nvidia drivers from loading at all. 

See also https://forums.opensuse.org/showthread.php/568651-Complications-migrating-from-Bumblebee-to-suse-prime

Maybe this is just an instruction under troubleshooting?

**Comment by sndirsch** [comment]
No, prime-select takes care of loading the kernel modules. Seems you have installed suse-prime, but it isn't configured. I suggest to configure it via `prime-select nvidia` or `prime-select offload`.

**Comment by sndirsch** [comment]
I meanwhile handled this issue in the (open)SUSE nvidia driver packages G04, G05, G06.

-------------------------------------------------------------------
Thu Jul 21 10:03:15 UTC 2022 - Stefan Dirsch <sndirsch@suse.com>

- %post(nvidia-glG06): run 'prime-select nvidia' even on system
  without Intel GPU visible on the PCI bus, if suse-prime
  package is mistakenly (still) installed to avoid nvidia kernel
  modules to be blacklisted

Closing therefore.
