### ISSUE TITLE
Is there any support for AMD + Nvidia laptop?

### ISSUE THREAD

**Issue by CicadaSeventeen** [openSUSE/SUSEPrime#80]
SUSE prime seems to only support Intel+Nvidia as designed. But now A+N laptops aare common too. Is there any support for them?

**Comment by sndirsch** [comment]
Yes, there is. But not as well tested as for Intel+NVIDIA. Just run 'prime-select nvidia' as you do for Intel+nVidia. There is also 'offload" mode. And if you want to disable nvidia card use "intel" (modeset for AMD GPU) or "amd" (amdgpu driver for AMD GPU).
