### ISSUE TITLE
When I use suseprime intel I want to use HDMI too

### ISSUE THREAD

**Issue by kshtsk** [openSUSE/SUSEPrime#82]
On my lenovo laptop it seems I cannot use HDMI when I switch to intel card, I can see the monitor is connected in settings but there is no output signal for it.

Looks like HDMI output associated with nvidia card.
```
xrandr --listproviders
Providers: number : 2
Provider 0: id: 0x7f; cap: 0xf (Source Output, Sink Output, Source Offload, Sink Offload); crtcs: 3; outputs: 1; associated providers: 1; name: modesetting
    output eDP-1
Provider 1: id: 0x47; cap: 0x2 (Sink Output); crtcs: 4; outputs: 4; associated providers: 1; name: modesetting
    output DP-1-1
    output DP-1-2
    output HDMI-1-1
    output DP-1-3
```

**Comment by sndirsch** [comment]
I think external outputs are connected physically to NVIDIA GPU on your laptop. So try with "prime-select nvidia" instead. I've received positive feedback by others, who could use their external outputs by using SUSEPrime in "nvidia" mode.

**Comment by kshtsk** [comment]
> I think external outputs are connected physically to NVIDIA GPU on your laptop. So try with "prime-select nvidia" instead. I've received positive feedback by others, who could use their external outputs by using SUSEPrime in "nvidia" mode.

@sndirsch thanks for the response, yes it works with Nvidia, but the whole idea that I don't want to use nvidia because of heating issues and fan spin noise, this is why I use SUSE prime select.

**Comment by bubbleguuum** [comment]
HDMI is most often than not physically wired to the dGPU, thus handled by the nvidia drivers that you need loaded.
There is no other choice if you want working HDMI.

**Comment by sndirsch** [comment]
Right. I'm afraid we can't overcome this hardware limitation.
