### ISSUE TITLE
prime-select.service fails to start

### ISSUE THREAD

**Issue by bakuserid** [openSUSE/SUSEPrime#83]
My laptop is taking an extremely long time to boot. The casue seems to be that the `prime-select.service` times out and fails to start. Here are the lines in which `prime` appears:

```
░░ Subject: A start job for unit prime-select.service has begun execution
░░ A start job for unit prime-select.service has begun execution.
Aug 06 14:12:25 16ITH6-openSUSE suse-prime[1518]: Boot: setting-up nvidia card
Aug 06 14:12:55 16ITH6-openSUSE systemd[1]: prime-select.service: start operation timed out. Terminating.
Aug 06 14:12:55 16ITH6-openSUSE systemd[1]: prime-select.service: Main process exited, code=killed, status=15/TERM
░░ An ExecStart= process belonging to unit prime-select.service has exited.
Aug 06 14:12:56 16ITH6-openSUSE systemd[1]: prime-select.service: Failed with result 'timeout'.
░░ The unit prime-select.service has entered the 'failed' state with result 'timeout'.
░░ Subject: A start job for unit prime-select.service has failed
░░ A start job for unit prime-select.service has finished with a failure.
Aug 06 14:12:56 16ITH6-openSUSE systemd[1]: prime-select.service: Consumed 2.182s CPU time.
░░ The unit prime-select.service completed and consumed the indicated resources.
```

Some background:

I am using a Lenovo Legion 5I Pro [16ITH6] with an Nvidia GeForce RTX-3050. I recently upgraded from the G05 series of Nvidia driver and related packages to the G06 series of Nvidia driver and related packages. Prior to this, this change SUSEPrime was working acceptably (except when using `bbswitch` which casused the entire laptop to poweroff).

When initially setting up SUSEPrime I followed instructions  regarding items that should be in `/etc/modprobe.d/`, `/etc/dracut.d/` and `/etc/udev/rules.d/`. Even though these have not been updated for the G06 series, they should be still valid.

In `/etc/modprobe.d/09-nvidia-modprobe-pm-G05.conf`,  I have
```
options nvidia NVreg_DynamicPowerManagement=0x02
```
-- modified from the original for fine internal Runtime D3 powwer control.

In `/etc/dracut.conf.d/90-nvidia-dracut-G05.conf`, I have
```
omit_drivers+=" nvidia nvidia-drm nvidia-modeset nvidia-uvm bbswitch "
```

and in `/etc/udev/rules.d/90-nvidia-udev-pm-G05.rules`

```
# Remove NVIDIA USB xHCI Host Controller devices, if present
ACTION=="add", SUBSYSTEM=="pci", ATTR{vendor}=="0x10de", ATTR{class}=="0x0c0330", ATTR{remove}="1"

# Remove NVIDIA USB Type-C UCSI devices, if present
ACTION=="add", SUBSYSTEM=="pci", ATTR{vendor}=="0x10de", ATTR{class}=="0x0c8000", ATTR{remove}="1"

# Remove NVIDIA Audio devices, if present
ACTION=="add", SUBSYSTEM=="pci", ATTR{vendor}=="0x10de", ATTR{class}=="0x040300", ATTR{remove}="1"

# Enable runtime PM for NVIDIA VGA/3D controller devices on driver bind
ACTION=="bind", SUBSYSTEM=="pci", ATTR{vendor}=="0x10de", ATTR{class}=="0x030000", TEST=="power/control", ATTR{power/control}="auto"
ACTION=="bind", SUBSYSTEM=="pci", ATTR{vendor}=="0x10de", ATTR{class}=="0x030200", TEST=="power/control", ATTR{power/control}="auto"

# Disable runtime PM for NVIDIA VGA/3D controller devices on driver unbind
ACTION=="unbind", SUBSYSTEM=="pci", ATTR{vendor}=="0x10de", ATTR{class}=="0x030000", TEST=="power/control", ATTR{power/control}="on"
ACTION=="unbind", SUBSYSTEM=="pci", ATTR{vendor}=="0x10de", ATTR{class}=="0x030200", TEST=="power/control", ATTR{power/control}="on"
```

Here are the contents of `/etc/systemd/system/multi-user.target.wants/prime-select.service

```
[Unit]
Description=SUSEPrime systemd service
Before=display-manager.service 

[Service]
Type=oneshot
ExecStart=/usr/sbin/prime-select systemd_call
TimeoutSec=30

[Install]
WantedBy=multi-user.target
```

and the services status

```
× prime-select.service - SUSEPrime systemd service
     Loaded: loaded (/usr/lib/systemd/system/prime-select.service; enabled; vendor preset: disabled)
     Active: failed (Result: timeout) since Sat 2022-08-06 14:12:56 EDT; 46min ago
    Process: 1352 ExecStart=/usr/sbin/prime-select systemd_call (code=killed, signal=TERM)
   Main PID: 1352 (code=killed, signal=TERM)
        CPU: 2.182s

Aug 06 14:12:25 16ITH6-openSUSE systemd[1]: Starting SUSEPrime systemd service...
Aug 06 14:12:55 16ITH6-openSUSE systemd[1]: prime-select.service: start operation timed out. Terminating.
Aug 06 14:12:55 16ITH6-openSUSE systemd[1]: prime-select.service: Main process exited, code=killed, status=15/TERM
Aug 06 14:12:56 16ITH6-openSUSE systemd[1]: prime-select.service: Failed with result 'timeout'.
Aug 06 14:12:56 16ITH6-openSUSE systemd[1]: Failed to start SUSEPrime systemd service.
Aug 06 14:12:56 16ITH6-openSUSE systemd[1]: prime-select.service: Consumed 2.182s CPU time.
```

The loaded nvidia modules:

```
nvidia_drm             73728  0
nvidia_modeset       1146880  1 nvidia_drm
nvidia_uvm           2715648  0
nvidia              40849408  2 nvidia_uvm,nvidia_modeset
nvidia_wmi_ec_backlight    16384  0
wmi                    45056  3 nvidia_wmi_ec_backlight,wmi_bmof,ideapad_laptop
```

The issue seems to be worse when using the kernel parameter `nvidia.prime=offload` at boot (SUSEPrime is configured for default `nvidia` mode).

Could you please address this issue. I would be happy to provide additional needed information that would help diagnose this issue.

Thanks,

BAK

**Comment by sndirsch** [comment]
Hmm. Could it be that you updated right from G05 to G06 driver packages? Unfortunately this does not work. Also it has conflicts you need to ignore to do it neverthless. So if you have done so, please remove G06 driver packages and reinstall them completely. 

I'm not aware of a prime kernel driver option for nvidia module. Not sure where you've found this.

**Comment by sndirsch** [comment]
> I'm not aware of a prime kernel driver option for nvidia module. Not sure where you've found this.

Such an option does not exist.

> options nvidia NVreg_DynamicPowerManagement=0x02

It's not our default, since I've seen issues on some systems with it and then changed it to 0x01.

**Comment by sndirsch** [comment]
Could you add here the output when running `prime-select log-view`?

**Comment by sndirsch** [comment]
Ok. Looks good so far now. Of course you can also set `NVreg_DynamicPowerManagement=0x02` if it's stable for you. You were totally right by setting `nvidia.prime=offload` as kernel boot option. This option is being evaluated by the startup script. And It's also documented. I think we can close this now as `WORKSFORME` with the fresh installation of G06 driver packages.
