### ISSUE TITLE
No HDMI audio output for Nvidia G06 driver

### ISSUE THREAD

**Issue by sith-on-mars** [openSUSE/SUSEPrime#85]
I'm on Tumbleweed Gnome. 

I switched to Nvidia when I connected the laptop to an external monitors through HDMI. I changed the Nvidia file according to [your guide](https://github.com/openSUSE/SUSEPrime#hdmi-audio-support-does-not-work) to make sure the audio would work. However, the external monitor didn't show up in the audio output setting. I'm not sure if it's the problem with 'suse-prime'.

**Comment by sith-on-mars** [comment]
Could it because the `90-nvidia-udev-pm-G05.rules` won't work for Nvidia G06 driver?

**Comment by sndirsch** [comment]
> Could it because the `90-nvidia-udev-pm-G05.rules` won't work with Nvidia G06 driver?

Since you're commenting out everything in there anyway, the content (and filename) no longer matters at all. So, no. This can't be the reason.

**Comment by sith-on-mars** [comment]
After rebooting my device it worked. Apologies for the confusion.
