### ISSUE TITLE
prime-select.sh does not find X session logout message in journal

### ISSUE THREAD

**Issue by h-fehlis** [openSUSE/SUSEPrime#92]
The part of _prime-select.sh_ which is supposed to run after X session logout never gets executed on my system that uses "autologin". The reason is that the following message gets dumped into the kernel log upon logout:

> pam_unix(lightdm-autologin:session): session closed

but the _"user_logout_waiter"_ part of _prime-select.sh_ waits for this message:

> pam_unix(lightdm:session): session closed

Changing the corresponding line in _prime-select.sh_ like this solves the problem:

> pam_unix(lightdm.*:session): session closed

(Sorry, no experience with pull requests.)

**Comment by sndirsch** [comment]
Thanks a lot! Fixed now. I also made a new release 0.8.11 and also updated the suse-prime package for Tumbleweed.
