### ISSUE TITLE
Add `prime-run` command

### ISSUE THREAD

**Issue by 00sapo** [openSUSE/SUSEPrime#96]
When the mode is set to offload, it would be useful having a script for selecting secondary GPU for specific commands. 

Arch provides `prime-run` (a one line bash script). I tested it in my installation and it works. It would be great having it installed together with this package...

https://gitlab.archlinux.org/archlinux/packaging/packages/nvidia-prime/-/blob/main/prime-run

**Comment by sndirsch** [comment]
Good idea! Added now.
