### ISSUE TITLE
laptop only or desktops as well?

### ISSUE THREAD

**Issue by Goddard** [openSUSE/SUSEPrime#97]
I know desktops don't have the same considerations such as power and what not that would make this as valuable, but on desktops like mine I have integrated graphics on my CPU and many desktop motherboards actually provide internal HDMI ports for screens that stay inside the case.

Currently the display doesn't even show up for me.  I was wondering if I used the integrated graphics from AMD and then only off load for games and things like that when needed using this software would help me achieve that while also being able to use those internal ports on the motherboard.

Also noticed only X11 stuff in the project.  Does this not support Wayland, or its just using the XWayland protocol? 

Any ideas?

**Comment by sndirsch** [comment]
Well, on desktops usually when adding a dedicated PCIe gfx card you just have a second VGA card on the PCI bus. Or it disables by default the internal gfx card. Or you can select, which one is active in the BIOS. Or which one of those is the primary VGA card. But this doesn't mean that you can use it for off loading. 

It's totally different on Laptops. There the second gfx card is  used usually for off-loading and external monitors nowadays.

SUSEPrime indeed only supports X11. Wayland is not supported. You can't run SUSEPrime on Xwayland.
